baseURL = "https://ksucs-hugo.russfeld.me"
languageCode = "en-us"
title = "K-State CS Hugo Framework"

# Change the default theme to be use when building the site with Hugo
theme = ["ksucs-hugo-theme", "plausible-hugo"]

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML", "Iframeable", "Teleprompter"]
section = [ "HTML", "Iframeable", "Teleprompter"]

[params]
  editURL = "https://gitlab.cs.ksu.edu/russfeld/ksucs-hugo/tree/master/content/"
  description = "K-State CS Hugo Framework"
  author = "Russell Feldhausen"
  showVisitedLinks = false
  themeVariant = "purple"
  disableLanguageSwitchingButton = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Custom output format for iframes
[outputFormats]
  [outputFormats.Iframeable]
    name = "Iframeable"
    baseName = "embed"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
  [outputFormats.Teleprompter]
    name = "Teleprompter"
    baseName = "tele"
    mediaType = "text/html"
    isPlainText = false
    isHtml = true

## Plausible config
[params.plausible]
  enable = true  # Whether to enable plausible tracking
  domain = "ksucs-hugo.russfeld.me"  # Plausible "domain" name/id in your dashboard
  selfhosted_domain = "plausible.russfeld.me"